Additional Tools: Part 1
amplience/dc-extension-rich-text pull request #15
Opened 2020-10-01 15:50 UTC by rs-amp

This PR adds some additional tools to the editor, and changes some existing ones:

- Soft Hyphen (`&shy;`)
  - Node that draws as a semi-transparent dash.
- Anchor Tag (`<a id="anchor-id"></a>`)
  - Note that draws as an anchor in a box with its id shown when hovering.
- Alignment (when not left aligned, `<p align="alignment">...</p>`)
  - Alignment within tables or other blocks is also done this way.
- Tables
  - Cells cannot be merged. The first row of the table will always be the table header. You should expect the same limitations as markdown tables, and set up your styles accordingly.
---
- Links now show their previous title and url when you attempt to create a link in the same position, making them easier to edit.
- Inline Styles can now be used in the JSON output mode.
- A document has been included that demonstrates different kinds of tool, and what their output result looks like.

PR description in progress, still being cleaned up.

2021-01-06 16:54 UTC, rs-amp commented
A few additional changes have been made:
- There is now a `title` parameter, which displays a title above the rich text editor when present.
- Since raw HTML tags are used for a few features, replace any reserved HTML characters like `<` with escaped variants like `&lt;`. This avoids some confusing errors.
- Alignment is now done via a `style` attribute (with text-align), or a `class` attribute of predefined name.
  - The inline style method produces code like `<p style="text-align:right;">...</p>`
  - The class method uses predefined classes. It is activated by passing `useClasses` as true in the initialisation parameters.
    - The classes are, by default, in the format `amp-align-<alignment>`, eg. `amp-align-left`. You can override these class names with a `classOverride` parameter: `"classOverride": {"amp-align-left": "custom-align-right"}
- When creating an anchor, it now enforces a globally unique anchor ID, and informs you when the provided ID is not valid.
- Changed some key behaviour with lists to better match Word, or other wysiwyg editors. It's not a perfect match, as our structure for lists is a bit different.

2021-02-02 08:19 UTC, PikinerLiliya approved these changes
Great job

2021-02-09 10:55 UTC, easen-amp reviewed
We have a change to host this extension rich-text.extensions.content.amplience.net, which will be released soon. Might be best to hold off merging this down until his hosting is in place.

2021-02-09 10:55 UTC, easen-amp commented on HOSTING.md
> +# Hosting the Rich Text Extension
We have a change to host this extension rich-text.extensions.content.amplience.net, which will be released soon. Might be best to hold off merging this down until his hosting is in place.

2021-02-17 15:22 UTC, rs-amp commented
Updated HOSTING.md to reflect the new hosting arrangements.

2021-02-22 16:44 UTC, easen-amp requested changes
Can the PR be renamed to start with "feat: " and include a sensible feature name as this will be recorded in the CHANGELOG.md when merge down.

2021-02-22 16:51 UTC, rs-amp commented
> Can the PR be renamed to start with "feat: " and include a sensible feature name as this will be recorded in the CHANGELOG.md when merge down.

Is the new name alright?

2021-02-25 14:01 UTC, easen-amp approved these changes

2021-03-04 09:48 UTC, merged